/* eslint-disable @typescript-eslint/no-redeclare */
export type Maybe<T> = T | null;
export type InputMaybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  Cursor: { input: string; output: string; }
  Map: { input: any; output: any; }
  Time: { input: string; output: string; }
};

export type __SHOULD_NOT_USE__ApiQuotaTracker = __SHOULD_NOT_USE__Node & {
  callCount: Scalars['Int']['output'];
  createdAt: Scalars['Time']['output'];
  id: Scalars['ID']['output'];
  lastCallAt: Maybe<Scalars['Time']['output']>;
  month: Scalars['Int']['output'];
  notificationSent: Scalars['Boolean']['output'];
  overrideEnabled: Scalars['Boolean']['output'];
  quotaExceeded: Scalars['Boolean']['output'];
  quotaLimit: Scalars['Int']['output'];
  year: Scalars['Int']['output'];
};

/**
 * APIQuotaTrackerWhereInput is used for filtering APIQuotaTracker objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__ApiQuotaTrackerWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__ApiQuotaTrackerWhereInput>>;
  /** call_count field predicates */
  callCount?: InputMaybe<Scalars['Int']['input']>;
  callCountGT?: InputMaybe<Scalars['Int']['input']>;
  callCountGTE?: InputMaybe<Scalars['Int']['input']>;
  callCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  callCountLT?: InputMaybe<Scalars['Int']['input']>;
  callCountLTE?: InputMaybe<Scalars['Int']['input']>;
  callCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  callCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** last_call_at field predicates */
  lastCallAt?: InputMaybe<Scalars['Time']['input']>;
  lastCallAtGT?: InputMaybe<Scalars['Time']['input']>;
  lastCallAtGTE?: InputMaybe<Scalars['Time']['input']>;
  lastCallAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  lastCallAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  lastCallAtLT?: InputMaybe<Scalars['Time']['input']>;
  lastCallAtLTE?: InputMaybe<Scalars['Time']['input']>;
  lastCallAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  lastCallAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  lastCallAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** month field predicates */
  month?: InputMaybe<Scalars['Int']['input']>;
  monthGT?: InputMaybe<Scalars['Int']['input']>;
  monthGTE?: InputMaybe<Scalars['Int']['input']>;
  monthIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  monthLT?: InputMaybe<Scalars['Int']['input']>;
  monthLTE?: InputMaybe<Scalars['Int']['input']>;
  monthNEQ?: InputMaybe<Scalars['Int']['input']>;
  monthNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__ApiQuotaTrackerWhereInput>;
  /** notification_sent field predicates */
  notificationSent?: InputMaybe<Scalars['Boolean']['input']>;
  notificationSentNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__ApiQuotaTrackerWhereInput>>;
  /** override_enabled field predicates */
  overrideEnabled?: InputMaybe<Scalars['Boolean']['input']>;
  overrideEnabledNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** quota_exceeded field predicates */
  quotaExceeded?: InputMaybe<Scalars['Boolean']['input']>;
  quotaExceededNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** quota_limit field predicates */
  quotaLimit?: InputMaybe<Scalars['Int']['input']>;
  quotaLimitGT?: InputMaybe<Scalars['Int']['input']>;
  quotaLimitGTE?: InputMaybe<Scalars['Int']['input']>;
  quotaLimitIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  quotaLimitLT?: InputMaybe<Scalars['Int']['input']>;
  quotaLimitLTE?: InputMaybe<Scalars['Int']['input']>;
  quotaLimitNEQ?: InputMaybe<Scalars['Int']['input']>;
  quotaLimitNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** year field predicates */
  year?: InputMaybe<Scalars['Int']['input']>;
  yearGT?: InputMaybe<Scalars['Int']['input']>;
  yearGTE?: InputMaybe<Scalars['Int']['input']>;
  yearIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  yearLT?: InputMaybe<Scalars['Int']['input']>;
  yearLTE?: InputMaybe<Scalars['Int']['input']>;
  yearNEQ?: InputMaybe<Scalars['Int']['input']>;
  yearNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

export type __SHOULD_NOT_USE__AuthPayload = {
  accessToken: Scalars['String']['output'];
  refreshToken: Scalars['String']['output'];
  user: __SHOULD_NOT_USE__User;
};

export type __SHOULD_NOT_USE__CreateProfileEntryInput = {
  gender: Scalars['String']['input'];
  linkedinUrn: Scalars['String']['input'];
};

export type __SHOULD_NOT_USE__CreateProfileInput = {
  name: Scalars['String']['input'];
  sourceFile: Scalars['String']['input'];
  title: Scalars['String']['input'];
  urn: Scalars['String']['input'];
};

export type __SHOULD_NOT_USE__CreateTodoInput = {
  name: Scalars['String']['input'];
  priority: Scalars['Int']['input'];
  status?: InputMaybe<TodoStatus>;
  userID: Scalars['ID']['input'];
};

export type __SHOULD_NOT_USE__CreateUserInput = {
  age: Scalars['Int']['input'];
  email: Scalars['String']['input'];
  name: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

export type __SHOULD_NOT_USE__CronJobConfig = __SHOULD_NOT_USE__Node & {
  adminEmail: Scalars['String']['output'];
  batchSize: Scalars['Int']['output'];
  createdAt: Scalars['Time']['output'];
  enabled: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  jobName: Scalars['String']['output'];
  jobType: CronJobType;
  lastRunAt: Maybe<Scalars['Time']['output']>;
  nextRunAt: Maybe<Scalars['Time']['output']>;
  respectQuota: Scalars['Boolean']['output'];
  schedule: Scalars['String']['output'];
  updatedAt: Scalars['Time']['output'];
};

/**
 * CronJobConfigWhereInput is used for filtering CronJobConfig objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__CronJobConfigWhereInput = {
  /** admin_email field predicates */
  adminEmail?: InputMaybe<Scalars['String']['input']>;
  adminEmailContains?: InputMaybe<Scalars['String']['input']>;
  adminEmailContainsFold?: InputMaybe<Scalars['String']['input']>;
  adminEmailEqualFold?: InputMaybe<Scalars['String']['input']>;
  adminEmailGT?: InputMaybe<Scalars['String']['input']>;
  adminEmailGTE?: InputMaybe<Scalars['String']['input']>;
  adminEmailHasPrefix?: InputMaybe<Scalars['String']['input']>;
  adminEmailHasSuffix?: InputMaybe<Scalars['String']['input']>;
  adminEmailIn?: InputMaybe<Array<Scalars['String']['input']>>;
  adminEmailLT?: InputMaybe<Scalars['String']['input']>;
  adminEmailLTE?: InputMaybe<Scalars['String']['input']>;
  adminEmailNEQ?: InputMaybe<Scalars['String']['input']>;
  adminEmailNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  and?: InputMaybe<Array<__SHOULD_NOT_USE__CronJobConfigWhereInput>>;
  /** batch_size field predicates */
  batchSize?: InputMaybe<Scalars['Int']['input']>;
  batchSizeGT?: InputMaybe<Scalars['Int']['input']>;
  batchSizeGTE?: InputMaybe<Scalars['Int']['input']>;
  batchSizeIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  batchSizeLT?: InputMaybe<Scalars['Int']['input']>;
  batchSizeLTE?: InputMaybe<Scalars['Int']['input']>;
  batchSizeNEQ?: InputMaybe<Scalars['Int']['input']>;
  batchSizeNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** enabled field predicates */
  enabled?: InputMaybe<Scalars['Boolean']['input']>;
  enabledNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** job_name field predicates */
  jobName?: InputMaybe<Scalars['String']['input']>;
  jobNameContains?: InputMaybe<Scalars['String']['input']>;
  jobNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  jobNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  jobNameGT?: InputMaybe<Scalars['String']['input']>;
  jobNameGTE?: InputMaybe<Scalars['String']['input']>;
  jobNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  jobNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  jobNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  jobNameLT?: InputMaybe<Scalars['String']['input']>;
  jobNameLTE?: InputMaybe<Scalars['String']['input']>;
  jobNameNEQ?: InputMaybe<Scalars['String']['input']>;
  jobNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** job_type field predicates */
  jobType?: InputMaybe<CronJobType>;
  jobTypeIn?: InputMaybe<Array<CronJobType>>;
  jobTypeNEQ?: InputMaybe<CronJobType>;
  jobTypeNotIn?: InputMaybe<Array<CronJobType>>;
  /** last_run_at field predicates */
  lastRunAt?: InputMaybe<Scalars['Time']['input']>;
  lastRunAtGT?: InputMaybe<Scalars['Time']['input']>;
  lastRunAtGTE?: InputMaybe<Scalars['Time']['input']>;
  lastRunAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  lastRunAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  lastRunAtLT?: InputMaybe<Scalars['Time']['input']>;
  lastRunAtLTE?: InputMaybe<Scalars['Time']['input']>;
  lastRunAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  lastRunAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  lastRunAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** next_run_at field predicates */
  nextRunAt?: InputMaybe<Scalars['Time']['input']>;
  nextRunAtGT?: InputMaybe<Scalars['Time']['input']>;
  nextRunAtGTE?: InputMaybe<Scalars['Time']['input']>;
  nextRunAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  nextRunAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  nextRunAtLT?: InputMaybe<Scalars['Time']['input']>;
  nextRunAtLTE?: InputMaybe<Scalars['Time']['input']>;
  nextRunAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  nextRunAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  nextRunAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  not?: InputMaybe<__SHOULD_NOT_USE__CronJobConfigWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__CronJobConfigWhereInput>>;
  /** respect_quota field predicates */
  respectQuota?: InputMaybe<Scalars['Boolean']['input']>;
  respectQuotaNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** schedule field predicates */
  schedule?: InputMaybe<Scalars['String']['input']>;
  scheduleContains?: InputMaybe<Scalars['String']['input']>;
  scheduleContainsFold?: InputMaybe<Scalars['String']['input']>;
  scheduleEqualFold?: InputMaybe<Scalars['String']['input']>;
  scheduleGT?: InputMaybe<Scalars['String']['input']>;
  scheduleGTE?: InputMaybe<Scalars['String']['input']>;
  scheduleHasPrefix?: InputMaybe<Scalars['String']['input']>;
  scheduleHasSuffix?: InputMaybe<Scalars['String']['input']>;
  scheduleIn?: InputMaybe<Array<Scalars['String']['input']>>;
  scheduleLT?: InputMaybe<Scalars['String']['input']>;
  scheduleLTE?: InputMaybe<Scalars['String']['input']>;
  scheduleNEQ?: InputMaybe<Scalars['String']['input']>;
  scheduleNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
};

export const CronJobType = {
  ProfileFetcher: 'PROFILE_FETCHER',
  QuotaReset: 'QUOTA_RESET'
} as const;

export type CronJobType = typeof CronJobType[keyof typeof CronJobType];
export type __SHOULD_NOT_USE__DashboardOverview = {
  cronJobsStatus: Array<__SHOULD_NOT_USE__CronJobConfig>;
  pendingProfilesCount: Scalars['Int']['output'];
  profileEntryStats: __SHOULD_NOT_USE__ProfileEntryStats;
  quotaStatus: Maybe<__SHOULD_NOT_USE__ApiQuotaTracker>;
  recentJobExecutions: Array<__SHOULD_NOT_USE__JobExecutionHistory>;
};

export type __SHOULD_NOT_USE__JobExecutionHistory = __SHOULD_NOT_USE__Node & {
  apiCallsMade: Scalars['Int']['output'];
  completedAt: Maybe<Scalars['Time']['output']>;
  createdAt: Scalars['Time']['output'];
  durationSeconds: Scalars['Int']['output'];
  errorSummary: Maybe<Scalars['String']['output']>;
  failedCount: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  jobName: Scalars['String']['output'];
  profileEntries: Array<__SHOULD_NOT_USE__ProfileEntry>;
  quotaRemaining: Scalars['Int']['output'];
  startedAt: Scalars['Time']['output'];
  status: JobExecutionStatus;
  successfulCount: Scalars['Int']['output'];
  totalProcessed: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__JobExecutionHistoryConnection = {
  edges: Maybe<Array<Maybe<__SHOULD_NOT_USE__JobExecutionHistoryEdge>>>;
  pageInfo: __SHOULD_NOT_USE__PageInfo;
  totalCount: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__JobExecutionHistoryEdge = {
  cursor: Scalars['Cursor']['output'];
  node: Maybe<__SHOULD_NOT_USE__JobExecutionHistory>;
};

/**
 * JobExecutionHistoryWhereInput is used for filtering JobExecutionHistory objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__JobExecutionHistoryWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__JobExecutionHistoryWhereInput>>;
  /** api_calls_made field predicates */
  apiCallsMade?: InputMaybe<Scalars['Int']['input']>;
  apiCallsMadeGT?: InputMaybe<Scalars['Int']['input']>;
  apiCallsMadeGTE?: InputMaybe<Scalars['Int']['input']>;
  apiCallsMadeIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  apiCallsMadeLT?: InputMaybe<Scalars['Int']['input']>;
  apiCallsMadeLTE?: InputMaybe<Scalars['Int']['input']>;
  apiCallsMadeNEQ?: InputMaybe<Scalars['Int']['input']>;
  apiCallsMadeNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** completed_at field predicates */
  completedAt?: InputMaybe<Scalars['Time']['input']>;
  completedAtGT?: InputMaybe<Scalars['Time']['input']>;
  completedAtGTE?: InputMaybe<Scalars['Time']['input']>;
  completedAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  completedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  completedAtLT?: InputMaybe<Scalars['Time']['input']>;
  completedAtLTE?: InputMaybe<Scalars['Time']['input']>;
  completedAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  completedAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  completedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** duration_seconds field predicates */
  durationSeconds?: InputMaybe<Scalars['Int']['input']>;
  durationSecondsGT?: InputMaybe<Scalars['Int']['input']>;
  durationSecondsGTE?: InputMaybe<Scalars['Int']['input']>;
  durationSecondsIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  durationSecondsLT?: InputMaybe<Scalars['Int']['input']>;
  durationSecondsLTE?: InputMaybe<Scalars['Int']['input']>;
  durationSecondsNEQ?: InputMaybe<Scalars['Int']['input']>;
  durationSecondsNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** error_summary field predicates */
  errorSummary?: InputMaybe<Scalars['String']['input']>;
  errorSummaryContains?: InputMaybe<Scalars['String']['input']>;
  errorSummaryContainsFold?: InputMaybe<Scalars['String']['input']>;
  errorSummaryEqualFold?: InputMaybe<Scalars['String']['input']>;
  errorSummaryGT?: InputMaybe<Scalars['String']['input']>;
  errorSummaryGTE?: InputMaybe<Scalars['String']['input']>;
  errorSummaryHasPrefix?: InputMaybe<Scalars['String']['input']>;
  errorSummaryHasSuffix?: InputMaybe<Scalars['String']['input']>;
  errorSummaryIn?: InputMaybe<Array<Scalars['String']['input']>>;
  errorSummaryIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  errorSummaryLT?: InputMaybe<Scalars['String']['input']>;
  errorSummaryLTE?: InputMaybe<Scalars['String']['input']>;
  errorSummaryNEQ?: InputMaybe<Scalars['String']['input']>;
  errorSummaryNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  errorSummaryNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** failed_count field predicates */
  failedCount?: InputMaybe<Scalars['Int']['input']>;
  failedCountGT?: InputMaybe<Scalars['Int']['input']>;
  failedCountGTE?: InputMaybe<Scalars['Int']['input']>;
  failedCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  failedCountLT?: InputMaybe<Scalars['Int']['input']>;
  failedCountLTE?: InputMaybe<Scalars['Int']['input']>;
  failedCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  failedCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** profile_entries edge predicates */
  hasProfileEntries?: InputMaybe<Scalars['Boolean']['input']>;
  hasProfileEntriesWith?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileEntryWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** job_name field predicates */
  jobName?: InputMaybe<Scalars['String']['input']>;
  jobNameContains?: InputMaybe<Scalars['String']['input']>;
  jobNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  jobNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  jobNameGT?: InputMaybe<Scalars['String']['input']>;
  jobNameGTE?: InputMaybe<Scalars['String']['input']>;
  jobNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  jobNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  jobNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  jobNameLT?: InputMaybe<Scalars['String']['input']>;
  jobNameLTE?: InputMaybe<Scalars['String']['input']>;
  jobNameNEQ?: InputMaybe<Scalars['String']['input']>;
  jobNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__JobExecutionHistoryWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__JobExecutionHistoryWhereInput>>;
  /** quota_remaining field predicates */
  quotaRemaining?: InputMaybe<Scalars['Int']['input']>;
  quotaRemainingGT?: InputMaybe<Scalars['Int']['input']>;
  quotaRemainingGTE?: InputMaybe<Scalars['Int']['input']>;
  quotaRemainingIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  quotaRemainingLT?: InputMaybe<Scalars['Int']['input']>;
  quotaRemainingLTE?: InputMaybe<Scalars['Int']['input']>;
  quotaRemainingNEQ?: InputMaybe<Scalars['Int']['input']>;
  quotaRemainingNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** started_at field predicates */
  startedAt?: InputMaybe<Scalars['Time']['input']>;
  startedAtGT?: InputMaybe<Scalars['Time']['input']>;
  startedAtGTE?: InputMaybe<Scalars['Time']['input']>;
  startedAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  startedAtLT?: InputMaybe<Scalars['Time']['input']>;
  startedAtLTE?: InputMaybe<Scalars['Time']['input']>;
  startedAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  startedAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** status field predicates */
  status?: InputMaybe<JobExecutionStatus>;
  statusIn?: InputMaybe<Array<JobExecutionStatus>>;
  statusNEQ?: InputMaybe<JobExecutionStatus>;
  statusNotIn?: InputMaybe<Array<JobExecutionStatus>>;
  /** successful_count field predicates */
  successfulCount?: InputMaybe<Scalars['Int']['input']>;
  successfulCountGT?: InputMaybe<Scalars['Int']['input']>;
  successfulCountGTE?: InputMaybe<Scalars['Int']['input']>;
  successfulCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  successfulCountLT?: InputMaybe<Scalars['Int']['input']>;
  successfulCountLTE?: InputMaybe<Scalars['Int']['input']>;
  successfulCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  successfulCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** total_processed field predicates */
  totalProcessed?: InputMaybe<Scalars['Int']['input']>;
  totalProcessedGT?: InputMaybe<Scalars['Int']['input']>;
  totalProcessedGTE?: InputMaybe<Scalars['Int']['input']>;
  totalProcessedIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  totalProcessedLT?: InputMaybe<Scalars['Int']['input']>;
  totalProcessedLTE?: InputMaybe<Scalars['Int']['input']>;
  totalProcessedNEQ?: InputMaybe<Scalars['Int']['input']>;
  totalProcessedNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

export const JobExecutionStatus = {
  Failed: 'FAILED',
  Partial: 'PARTIAL',
  QuotaExceeded: 'QUOTA_EXCEEDED',
  Success: 'SUCCESS'
} as const;

export type JobExecutionStatus = typeof JobExecutionStatus[keyof typeof JobExecutionStatus];
export type __SHOULD_NOT_USE__JobStats = {
  averageDuration: Scalars['Int']['output'];
  successRate: Scalars['Float']['output'];
  totalAPICallsMade: Scalars['Int']['output'];
  totalExecutions: Scalars['Int']['output'];
  totalProfiles: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__LoginInput = {
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

export type __SHOULD_NOT_USE__Mutation = {
  createProfile: __SHOULD_NOT_USE__Profile;
  createProfileEntry: __SHOULD_NOT_USE__ProfileEntry;
  createTodo: __SHOULD_NOT_USE__Todo;
  createUser: __SHOULD_NOT_USE__User;
  deleteProfileEntry: Scalars['Boolean']['output'];
  fetchProfileEntry: Scalars['Boolean']['output'];
  login: Maybe<__SHOULD_NOT_USE__AuthPayload>;
  refreshToken: Maybe<__SHOULD_NOT_USE__RefreshTokenPayload>;
  setQuotaOverride: __SHOULD_NOT_USE__ApiQuotaTracker;
  toggleCronJob: __SHOULD_NOT_USE__CronJobConfig;
  triggerProfileFetch: __SHOULD_NOT_USE__JobExecutionHistory;
  updateCronJobConfig: __SHOULD_NOT_USE__CronJobConfig;
  updateProfile: __SHOULD_NOT_USE__Profile;
  updateProfileEntry: __SHOULD_NOT_USE__ProfileEntry;
  updateQuotaLimit: __SHOULD_NOT_USE__ApiQuotaTracker;
  updateTodo: __SHOULD_NOT_USE__Todo;
  updateUser: __SHOULD_NOT_USE__User;
};


export type __SHOULD_NOT_USE__MutationCreateProfileArgs = {
  input: __SHOULD_NOT_USE__CreateProfileInput;
};


export type __SHOULD_NOT_USE__MutationCreateProfileEntryArgs = {
  input: __SHOULD_NOT_USE__CreateProfileEntryInput;
};


export type __SHOULD_NOT_USE__MutationCreateTodoArgs = {
  input: __SHOULD_NOT_USE__CreateTodoInput;
};


export type __SHOULD_NOT_USE__MutationCreateUserArgs = {
  input: __SHOULD_NOT_USE__CreateUserInput;
};


export type __SHOULD_NOT_USE__MutationDeleteProfileEntryArgs = {
  id: Scalars['ID']['input'];
};


export type __SHOULD_NOT_USE__MutationFetchProfileEntryArgs = {
  id: Scalars['ID']['input'];
};


export type __SHOULD_NOT_USE__MutationLoginArgs = {
  input: __SHOULD_NOT_USE__LoginInput;
};


export type __SHOULD_NOT_USE__MutationSetQuotaOverrideArgs = {
  enabled: Scalars['Boolean']['input'];
};


export type __SHOULD_NOT_USE__MutationToggleCronJobArgs = {
  enabled: Scalars['Boolean']['input'];
  jobName: Scalars['String']['input'];
};


export type __SHOULD_NOT_USE__MutationUpdateCronJobConfigArgs = {
  input: __SHOULD_NOT_USE__UpdateCronJobConfigInput;
  jobName: Scalars['String']['input'];
};


export type __SHOULD_NOT_USE__MutationUpdateProfileArgs = {
  input: __SHOULD_NOT_USE__UpdateProfileInput;
};


export type __SHOULD_NOT_USE__MutationUpdateProfileEntryArgs = {
  id: Scalars['ID']['input'];
  input: __SHOULD_NOT_USE__UpdateProfileEntryInput;
};


export type __SHOULD_NOT_USE__MutationUpdateQuotaLimitArgs = {
  limit: Scalars['Int']['input'];
};


export type __SHOULD_NOT_USE__MutationUpdateTodoArgs = {
  input: __SHOULD_NOT_USE__UpdateTodoInput;
};


export type __SHOULD_NOT_USE__MutationUpdateUserArgs = {
  input: __SHOULD_NOT_USE__UpdateUserInput;
};

export type __SHOULD_NOT_USE__Node = {
  id: Scalars['ID']['output'];
};

export type __SHOULD_NOT_USE__PageInfo = {
  endCursor: Maybe<Scalars['Cursor']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  hasPreviousPage: Scalars['Boolean']['output'];
  startCursor: Maybe<Scalars['Cursor']['output']>;
};

export type __SHOULD_NOT_USE__Profile = __SHOULD_NOT_USE__Node & {
  city: Maybe<Scalars['String']['output']>;
  cleanedDataS3Key: Maybe<Scalars['String']['output']>;
  country: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['String']['output'];
  educations: Maybe<Scalars['Map']['output']>;
  firstName: Maybe<Scalars['String']['output']>;
  geoData: Maybe<Scalars['Map']['output']>;
  headline: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  lastName: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  positions: Maybe<Scalars['Map']['output']>;
  profileEntry: Maybe<__SHOULD_NOT_USE__ProfileEntry>;
  rawDataS3Key: Maybe<Scalars['String']['output']>;
  skills: Maybe<Scalars['Map']['output']>;
  sourceFile: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  updatedAt: Scalars['String']['output'];
  urn: Scalars['String']['output'];
  username: Maybe<Scalars['String']['output']>;
};

export type __SHOULD_NOT_USE__ProfileConnection = {
  edges: Maybe<Array<Maybe<__SHOULD_NOT_USE__ProfileEdge>>>;
  pageInfo: __SHOULD_NOT_USE__PageInfo;
  totalCount: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__ProfileEdge = {
  cursor: Scalars['Cursor']['output'];
  node: Maybe<__SHOULD_NOT_USE__Profile>;
};

export type __SHOULD_NOT_USE__ProfileEntry = __SHOULD_NOT_USE__Node & {
  createdAt: Scalars['Time']['output'];
  fetchCount: Scalars['Int']['output'];
  gender: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  lastFetchedAt: Maybe<Scalars['Time']['output']>;
  linkedinUrn: Scalars['String']['output'];
  profileData: Maybe<Scalars['Map']['output']>;
  status: ProfileEntryStatus;
  updatedAt: Scalars['Time']['output'];
};

export type __SHOULD_NOT_USE__ProfileEntryConnection = {
  edges: Maybe<Array<Maybe<__SHOULD_NOT_USE__ProfileEntryEdge>>>;
  pageInfo: __SHOULD_NOT_USE__PageInfo;
  totalCount: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__ProfileEntryEdge = {
  cursor: Scalars['Cursor']['output'];
  node: Maybe<__SHOULD_NOT_USE__ProfileEntry>;
};

export type __SHOULD_NOT_USE__ProfileEntryStats = {
  completedCount: Scalars['Int']['output'];
  failedCount: Scalars['Int']['output'];
  fetchingCount: Scalars['Int']['output'];
  pendingCount: Scalars['Int']['output'];
  totalCount: Scalars['Int']['output'];
};

export const ProfileEntryStatus = {
  Completed: 'COMPLETED',
  Failed: 'FAILED',
  Fetching: 'FETCHING',
  Pending: 'PENDING'
} as const;

export type ProfileEntryStatus = typeof ProfileEntryStatus[keyof typeof ProfileEntryStatus];
/**
 * ProfileEntryWhereInput is used for filtering ProfileEntry objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__ProfileEntryWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileEntryWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** error_message field predicates */
  errorMessage?: InputMaybe<Scalars['String']['input']>;
  errorMessageContains?: InputMaybe<Scalars['String']['input']>;
  errorMessageContainsFold?: InputMaybe<Scalars['String']['input']>;
  errorMessageEqualFold?: InputMaybe<Scalars['String']['input']>;
  errorMessageGT?: InputMaybe<Scalars['String']['input']>;
  errorMessageGTE?: InputMaybe<Scalars['String']['input']>;
  errorMessageHasPrefix?: InputMaybe<Scalars['String']['input']>;
  errorMessageHasSuffix?: InputMaybe<Scalars['String']['input']>;
  errorMessageIn?: InputMaybe<Array<Scalars['String']['input']>>;
  errorMessageIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  errorMessageLT?: InputMaybe<Scalars['String']['input']>;
  errorMessageLTE?: InputMaybe<Scalars['String']['input']>;
  errorMessageNEQ?: InputMaybe<Scalars['String']['input']>;
  errorMessageNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  errorMessageNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** fetch_count field predicates */
  fetchCount?: InputMaybe<Scalars['Int']['input']>;
  fetchCountGT?: InputMaybe<Scalars['Int']['input']>;
  fetchCountGTE?: InputMaybe<Scalars['Int']['input']>;
  fetchCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  fetchCountLT?: InputMaybe<Scalars['Int']['input']>;
  fetchCountLTE?: InputMaybe<Scalars['Int']['input']>;
  fetchCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  fetchCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** gender field predicates */
  gender?: InputMaybe<Scalars['String']['input']>;
  genderContains?: InputMaybe<Scalars['String']['input']>;
  genderContainsFold?: InputMaybe<Scalars['String']['input']>;
  genderEqualFold?: InputMaybe<Scalars['String']['input']>;
  genderGT?: InputMaybe<Scalars['String']['input']>;
  genderGTE?: InputMaybe<Scalars['String']['input']>;
  genderHasPrefix?: InputMaybe<Scalars['String']['input']>;
  genderHasSuffix?: InputMaybe<Scalars['String']['input']>;
  genderIn?: InputMaybe<Array<Scalars['String']['input']>>;
  genderIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  genderLT?: InputMaybe<Scalars['String']['input']>;
  genderLTE?: InputMaybe<Scalars['String']['input']>;
  genderNEQ?: InputMaybe<Scalars['String']['input']>;
  genderNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  genderNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** job_executions edge predicates */
  hasJobExecutions?: InputMaybe<Scalars['Boolean']['input']>;
  hasJobExecutionsWith?: InputMaybe<Array<__SHOULD_NOT_USE__JobExecutionHistoryWhereInput>>;
  /** profile edge predicates */
  hasProfile?: InputMaybe<Scalars['Boolean']['input']>;
  hasProfileWith?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** last_fetched_at field predicates */
  lastFetchedAt?: InputMaybe<Scalars['Time']['input']>;
  lastFetchedAtGT?: InputMaybe<Scalars['Time']['input']>;
  lastFetchedAtGTE?: InputMaybe<Scalars['Time']['input']>;
  lastFetchedAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  lastFetchedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  lastFetchedAtLT?: InputMaybe<Scalars['Time']['input']>;
  lastFetchedAtLTE?: InputMaybe<Scalars['Time']['input']>;
  lastFetchedAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  lastFetchedAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  lastFetchedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** linkedin_urn field predicates */
  linkedinUrn?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnContains?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnContainsFold?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnEqualFold?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnGT?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnGTE?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnHasPrefix?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnHasSuffix?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnIn?: InputMaybe<Array<Scalars['String']['input']>>;
  linkedinUrnLT?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnLTE?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnNEQ?: InputMaybe<Scalars['String']['input']>;
  linkedinUrnNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__ProfileEntryWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileEntryWhereInput>>;
  /** raw_response_s3_key field predicates */
  rawResponseS3Key?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyContains?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyContainsFold?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyEqualFold?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyGT?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyGTE?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyHasPrefix?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyHasSuffix?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyIn?: InputMaybe<Array<Scalars['String']['input']>>;
  rawResponseS3KeyIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  rawResponseS3KeyLT?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyLTE?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyNEQ?: InputMaybe<Scalars['String']['input']>;
  rawResponseS3KeyNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  rawResponseS3KeyNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** status field predicates */
  status?: InputMaybe<ProfileEntryStatus>;
  statusIn?: InputMaybe<Array<ProfileEntryStatus>>;
  statusNEQ?: InputMaybe<ProfileEntryStatus>;
  statusNotIn?: InputMaybe<Array<ProfileEntryStatus>>;
  /** template_json_s3_key field predicates */
  templateJSONS3Key?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyContains?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyContainsFold?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyEqualFold?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyGT?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyGTE?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyHasPrefix?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyHasSuffix?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyIn?: InputMaybe<Array<Scalars['String']['input']>>;
  templateJSONS3KeyIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  templateJSONS3KeyLT?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyLTE?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyNEQ?: InputMaybe<Scalars['String']['input']>;
  templateJSONS3KeyNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  templateJSONS3KeyNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type __SHOULD_NOT_USE__ProfilePost = __SHOULD_NOT_USE__Node & {
  createdAt: Scalars['Time']['output'];
  errorMessage: Maybe<Scalars['String']['output']>;
  fetchStatus: ProfilePostFetchStatus;
  id: Scalars['ID']['output'];
  items: Array<__SHOULD_NOT_USE__ProfilePostItem>;
  profileUsername: Scalars['String']['output'];
  s3Key: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['Time']['output'];
};

export const ProfilePostFetchStatus = {
  Completed: 'COMPLETED',
  Failed: 'FAILED',
  NotFound: 'NOT_FOUND',
  Pending: 'PENDING'
} as const;

export type ProfilePostFetchStatus = typeof ProfilePostFetchStatus[keyof typeof ProfilePostFetchStatus];
export type __SHOULD_NOT_USE__ProfilePostItem = __SHOULD_NOT_USE__Node & {
  commentsCount: Scalars['Int']['output'];
  contentType: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['Time']['output'];
  empathyCount: Scalars['Int']['output'];
  funnyCount: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  interestCount: Scalars['Int']['output'];
  isRepost: Scalars['Boolean']['output'];
  likeCount: Scalars['Int']['output'];
  postUrl: Maybe<Scalars['String']['output']>;
  postUrn: Maybe<Scalars['String']['output']>;
  postedAt: Maybe<Scalars['Time']['output']>;
  praiseCount: Scalars['Int']['output'];
  profileUsername: Scalars['String']['output'];
  repostsCount: Scalars['Int']['output'];
  text: Maybe<Scalars['String']['output']>;
  totalReactions: Scalars['Int']['output'];
  updatedAt: Scalars['Time']['output'];
};

/**
 * ProfilePostItemWhereInput is used for filtering ProfilePostItem objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__ProfilePostItemWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__ProfilePostItemWhereInput>>;
  /** comments_count field predicates */
  commentsCount?: InputMaybe<Scalars['Int']['input']>;
  commentsCountGT?: InputMaybe<Scalars['Int']['input']>;
  commentsCountGTE?: InputMaybe<Scalars['Int']['input']>;
  commentsCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  commentsCountLT?: InputMaybe<Scalars['Int']['input']>;
  commentsCountLTE?: InputMaybe<Scalars['Int']['input']>;
  commentsCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  commentsCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** content_type field predicates */
  contentType?: InputMaybe<Scalars['String']['input']>;
  contentTypeContains?: InputMaybe<Scalars['String']['input']>;
  contentTypeContainsFold?: InputMaybe<Scalars['String']['input']>;
  contentTypeEqualFold?: InputMaybe<Scalars['String']['input']>;
  contentTypeGT?: InputMaybe<Scalars['String']['input']>;
  contentTypeGTE?: InputMaybe<Scalars['String']['input']>;
  contentTypeHasPrefix?: InputMaybe<Scalars['String']['input']>;
  contentTypeHasSuffix?: InputMaybe<Scalars['String']['input']>;
  contentTypeIn?: InputMaybe<Array<Scalars['String']['input']>>;
  contentTypeIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  contentTypeLT?: InputMaybe<Scalars['String']['input']>;
  contentTypeLTE?: InputMaybe<Scalars['String']['input']>;
  contentTypeNEQ?: InputMaybe<Scalars['String']['input']>;
  contentTypeNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  contentTypeNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** empathy_count field predicates */
  empathyCount?: InputMaybe<Scalars['Int']['input']>;
  empathyCountGT?: InputMaybe<Scalars['Int']['input']>;
  empathyCountGTE?: InputMaybe<Scalars['Int']['input']>;
  empathyCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  empathyCountLT?: InputMaybe<Scalars['Int']['input']>;
  empathyCountLTE?: InputMaybe<Scalars['Int']['input']>;
  empathyCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  empathyCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** funny_count field predicates */
  funnyCount?: InputMaybe<Scalars['Int']['input']>;
  funnyCountGT?: InputMaybe<Scalars['Int']['input']>;
  funnyCountGTE?: InputMaybe<Scalars['Int']['input']>;
  funnyCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  funnyCountLT?: InputMaybe<Scalars['Int']['input']>;
  funnyCountLTE?: InputMaybe<Scalars['Int']['input']>;
  funnyCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  funnyCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** profile_post edge predicates */
  hasProfilePost?: InputMaybe<Scalars['Boolean']['input']>;
  hasProfilePostWith?: InputMaybe<Array<__SHOULD_NOT_USE__ProfilePostWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** interest_count field predicates */
  interestCount?: InputMaybe<Scalars['Int']['input']>;
  interestCountGT?: InputMaybe<Scalars['Int']['input']>;
  interestCountGTE?: InputMaybe<Scalars['Int']['input']>;
  interestCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  interestCountLT?: InputMaybe<Scalars['Int']['input']>;
  interestCountLTE?: InputMaybe<Scalars['Int']['input']>;
  interestCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  interestCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** is_repost field predicates */
  isRepost?: InputMaybe<Scalars['Boolean']['input']>;
  isRepostNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** like_count field predicates */
  likeCount?: InputMaybe<Scalars['Int']['input']>;
  likeCountGT?: InputMaybe<Scalars['Int']['input']>;
  likeCountGTE?: InputMaybe<Scalars['Int']['input']>;
  likeCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  likeCountLT?: InputMaybe<Scalars['Int']['input']>;
  likeCountLTE?: InputMaybe<Scalars['Int']['input']>;
  likeCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  likeCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__ProfilePostItemWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__ProfilePostItemWhereInput>>;
  /** post_url field predicates */
  postURL?: InputMaybe<Scalars['String']['input']>;
  postURLContains?: InputMaybe<Scalars['String']['input']>;
  postURLContainsFold?: InputMaybe<Scalars['String']['input']>;
  postURLEqualFold?: InputMaybe<Scalars['String']['input']>;
  postURLGT?: InputMaybe<Scalars['String']['input']>;
  postURLGTE?: InputMaybe<Scalars['String']['input']>;
  postURLHasPrefix?: InputMaybe<Scalars['String']['input']>;
  postURLHasSuffix?: InputMaybe<Scalars['String']['input']>;
  postURLIn?: InputMaybe<Array<Scalars['String']['input']>>;
  postURLIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  postURLLT?: InputMaybe<Scalars['String']['input']>;
  postURLLTE?: InputMaybe<Scalars['String']['input']>;
  postURLNEQ?: InputMaybe<Scalars['String']['input']>;
  postURLNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  postURLNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** post_urn field predicates */
  postUrn?: InputMaybe<Scalars['String']['input']>;
  postUrnContains?: InputMaybe<Scalars['String']['input']>;
  postUrnContainsFold?: InputMaybe<Scalars['String']['input']>;
  postUrnEqualFold?: InputMaybe<Scalars['String']['input']>;
  postUrnGT?: InputMaybe<Scalars['String']['input']>;
  postUrnGTE?: InputMaybe<Scalars['String']['input']>;
  postUrnHasPrefix?: InputMaybe<Scalars['String']['input']>;
  postUrnHasSuffix?: InputMaybe<Scalars['String']['input']>;
  postUrnIn?: InputMaybe<Array<Scalars['String']['input']>>;
  postUrnIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  postUrnLT?: InputMaybe<Scalars['String']['input']>;
  postUrnLTE?: InputMaybe<Scalars['String']['input']>;
  postUrnNEQ?: InputMaybe<Scalars['String']['input']>;
  postUrnNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  postUrnNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** posted_at field predicates */
  postedAt?: InputMaybe<Scalars['Time']['input']>;
  postedAtGT?: InputMaybe<Scalars['Time']['input']>;
  postedAtGTE?: InputMaybe<Scalars['Time']['input']>;
  postedAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  postedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  postedAtLT?: InputMaybe<Scalars['Time']['input']>;
  postedAtLTE?: InputMaybe<Scalars['Time']['input']>;
  postedAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  postedAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  postedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** praise_count field predicates */
  praiseCount?: InputMaybe<Scalars['Int']['input']>;
  praiseCountGT?: InputMaybe<Scalars['Int']['input']>;
  praiseCountGTE?: InputMaybe<Scalars['Int']['input']>;
  praiseCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  praiseCountLT?: InputMaybe<Scalars['Int']['input']>;
  praiseCountLTE?: InputMaybe<Scalars['Int']['input']>;
  praiseCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  praiseCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** profile_username field predicates */
  profileUsername?: InputMaybe<Scalars['String']['input']>;
  profileUsernameContains?: InputMaybe<Scalars['String']['input']>;
  profileUsernameContainsFold?: InputMaybe<Scalars['String']['input']>;
  profileUsernameEqualFold?: InputMaybe<Scalars['String']['input']>;
  profileUsernameGT?: InputMaybe<Scalars['String']['input']>;
  profileUsernameGTE?: InputMaybe<Scalars['String']['input']>;
  profileUsernameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  profileUsernameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  profileUsernameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  profileUsernameLT?: InputMaybe<Scalars['String']['input']>;
  profileUsernameLTE?: InputMaybe<Scalars['String']['input']>;
  profileUsernameNEQ?: InputMaybe<Scalars['String']['input']>;
  profileUsernameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** reposts_count field predicates */
  repostsCount?: InputMaybe<Scalars['Int']['input']>;
  repostsCountGT?: InputMaybe<Scalars['Int']['input']>;
  repostsCountGTE?: InputMaybe<Scalars['Int']['input']>;
  repostsCountIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  repostsCountLT?: InputMaybe<Scalars['Int']['input']>;
  repostsCountLTE?: InputMaybe<Scalars['Int']['input']>;
  repostsCountNEQ?: InputMaybe<Scalars['Int']['input']>;
  repostsCountNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** text field predicates */
  text?: InputMaybe<Scalars['String']['input']>;
  textContains?: InputMaybe<Scalars['String']['input']>;
  textContainsFold?: InputMaybe<Scalars['String']['input']>;
  textEqualFold?: InputMaybe<Scalars['String']['input']>;
  textGT?: InputMaybe<Scalars['String']['input']>;
  textGTE?: InputMaybe<Scalars['String']['input']>;
  textHasPrefix?: InputMaybe<Scalars['String']['input']>;
  textHasSuffix?: InputMaybe<Scalars['String']['input']>;
  textIn?: InputMaybe<Array<Scalars['String']['input']>>;
  textIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  textLT?: InputMaybe<Scalars['String']['input']>;
  textLTE?: InputMaybe<Scalars['String']['input']>;
  textNEQ?: InputMaybe<Scalars['String']['input']>;
  textNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  textNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** total_reactions field predicates */
  totalReactions?: InputMaybe<Scalars['Int']['input']>;
  totalReactionsGT?: InputMaybe<Scalars['Int']['input']>;
  totalReactionsGTE?: InputMaybe<Scalars['Int']['input']>;
  totalReactionsIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  totalReactionsLT?: InputMaybe<Scalars['Int']['input']>;
  totalReactionsLTE?: InputMaybe<Scalars['Int']['input']>;
  totalReactionsNEQ?: InputMaybe<Scalars['Int']['input']>;
  totalReactionsNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

/**
 * ProfilePostWhereInput is used for filtering ProfilePost objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__ProfilePostWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__ProfilePostWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** error_message field predicates */
  errorMessage?: InputMaybe<Scalars['String']['input']>;
  errorMessageContains?: InputMaybe<Scalars['String']['input']>;
  errorMessageContainsFold?: InputMaybe<Scalars['String']['input']>;
  errorMessageEqualFold?: InputMaybe<Scalars['String']['input']>;
  errorMessageGT?: InputMaybe<Scalars['String']['input']>;
  errorMessageGTE?: InputMaybe<Scalars['String']['input']>;
  errorMessageHasPrefix?: InputMaybe<Scalars['String']['input']>;
  errorMessageHasSuffix?: InputMaybe<Scalars['String']['input']>;
  errorMessageIn?: InputMaybe<Array<Scalars['String']['input']>>;
  errorMessageIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  errorMessageLT?: InputMaybe<Scalars['String']['input']>;
  errorMessageLTE?: InputMaybe<Scalars['String']['input']>;
  errorMessageNEQ?: InputMaybe<Scalars['String']['input']>;
  errorMessageNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  errorMessageNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** fetch_status field predicates */
  fetchStatus?: InputMaybe<ProfilePostFetchStatus>;
  fetchStatusIn?: InputMaybe<Array<ProfilePostFetchStatus>>;
  fetchStatusNEQ?: InputMaybe<ProfilePostFetchStatus>;
  fetchStatusNotIn?: InputMaybe<Array<ProfilePostFetchStatus>>;
  /** items edge predicates */
  hasItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasItemsWith?: InputMaybe<Array<__SHOULD_NOT_USE__ProfilePostItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__ProfilePostWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__ProfilePostWhereInput>>;
  /** profile_username field predicates */
  profileUsername?: InputMaybe<Scalars['String']['input']>;
  profileUsernameContains?: InputMaybe<Scalars['String']['input']>;
  profileUsernameContainsFold?: InputMaybe<Scalars['String']['input']>;
  profileUsernameEqualFold?: InputMaybe<Scalars['String']['input']>;
  profileUsernameGT?: InputMaybe<Scalars['String']['input']>;
  profileUsernameGTE?: InputMaybe<Scalars['String']['input']>;
  profileUsernameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  profileUsernameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  profileUsernameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  profileUsernameLT?: InputMaybe<Scalars['String']['input']>;
  profileUsernameLTE?: InputMaybe<Scalars['String']['input']>;
  profileUsernameNEQ?: InputMaybe<Scalars['String']['input']>;
  profileUsernameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** s3_key field predicates */
  s3Key?: InputMaybe<Scalars['String']['input']>;
  s3KeyContains?: InputMaybe<Scalars['String']['input']>;
  s3KeyContainsFold?: InputMaybe<Scalars['String']['input']>;
  s3KeyEqualFold?: InputMaybe<Scalars['String']['input']>;
  s3KeyGT?: InputMaybe<Scalars['String']['input']>;
  s3KeyGTE?: InputMaybe<Scalars['String']['input']>;
  s3KeyHasPrefix?: InputMaybe<Scalars['String']['input']>;
  s3KeyHasSuffix?: InputMaybe<Scalars['String']['input']>;
  s3KeyIn?: InputMaybe<Array<Scalars['String']['input']>>;
  s3KeyIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  s3KeyLT?: InputMaybe<Scalars['String']['input']>;
  s3KeyLTE?: InputMaybe<Scalars['String']['input']>;
  s3KeyNEQ?: InputMaybe<Scalars['String']['input']>;
  s3KeyNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  s3KeyNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type __SHOULD_NOT_USE__ProfileTitleGroup = {
  count: Scalars['Int']['output'];
  title: Scalars['String']['output'];
};

/**
 * ProfileWhereInput is used for filtering Profile objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__ProfileWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileWhereInput>>;
  /** city field predicates */
  city?: InputMaybe<Scalars['String']['input']>;
  cityContains?: InputMaybe<Scalars['String']['input']>;
  cityContainsFold?: InputMaybe<Scalars['String']['input']>;
  cityEqualFold?: InputMaybe<Scalars['String']['input']>;
  cityGT?: InputMaybe<Scalars['String']['input']>;
  cityGTE?: InputMaybe<Scalars['String']['input']>;
  cityHasPrefix?: InputMaybe<Scalars['String']['input']>;
  cityHasSuffix?: InputMaybe<Scalars['String']['input']>;
  cityIn?: InputMaybe<Array<Scalars['String']['input']>>;
  cityIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  cityLT?: InputMaybe<Scalars['String']['input']>;
  cityLTE?: InputMaybe<Scalars['String']['input']>;
  cityNEQ?: InputMaybe<Scalars['String']['input']>;
  cityNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  cityNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** cleaned_data_s3_key field predicates */
  cleanedDataS3Key?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyContains?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyContainsFold?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyEqualFold?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyGT?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyGTE?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyHasPrefix?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyHasSuffix?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyIn?: InputMaybe<Array<Scalars['String']['input']>>;
  cleanedDataS3KeyIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  cleanedDataS3KeyLT?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyLTE?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyNEQ?: InputMaybe<Scalars['String']['input']>;
  cleanedDataS3KeyNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  cleanedDataS3KeyNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** country field predicates */
  country?: InputMaybe<Scalars['String']['input']>;
  countryContains?: InputMaybe<Scalars['String']['input']>;
  countryContainsFold?: InputMaybe<Scalars['String']['input']>;
  countryEqualFold?: InputMaybe<Scalars['String']['input']>;
  countryGT?: InputMaybe<Scalars['String']['input']>;
  countryGTE?: InputMaybe<Scalars['String']['input']>;
  countryHasPrefix?: InputMaybe<Scalars['String']['input']>;
  countryHasSuffix?: InputMaybe<Scalars['String']['input']>;
  countryIn?: InputMaybe<Array<Scalars['String']['input']>>;
  countryIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  countryLT?: InputMaybe<Scalars['String']['input']>;
  countryLTE?: InputMaybe<Scalars['String']['input']>;
  countryNEQ?: InputMaybe<Scalars['String']['input']>;
  countryNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  countryNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** first_name field predicates */
  firstName?: InputMaybe<Scalars['String']['input']>;
  firstNameContains?: InputMaybe<Scalars['String']['input']>;
  firstNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  firstNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  firstNameGT?: InputMaybe<Scalars['String']['input']>;
  firstNameGTE?: InputMaybe<Scalars['String']['input']>;
  firstNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  firstNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  firstNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  firstNameIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  firstNameLT?: InputMaybe<Scalars['String']['input']>;
  firstNameLTE?: InputMaybe<Scalars['String']['input']>;
  firstNameNEQ?: InputMaybe<Scalars['String']['input']>;
  firstNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  firstNameNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** profile_entry edge predicates */
  hasProfileEntry?: InputMaybe<Scalars['Boolean']['input']>;
  hasProfileEntryWith?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileEntryWhereInput>>;
  /** headline field predicates */
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineContains?: InputMaybe<Scalars['String']['input']>;
  headlineContainsFold?: InputMaybe<Scalars['String']['input']>;
  headlineEqualFold?: InputMaybe<Scalars['String']['input']>;
  headlineGT?: InputMaybe<Scalars['String']['input']>;
  headlineGTE?: InputMaybe<Scalars['String']['input']>;
  headlineHasPrefix?: InputMaybe<Scalars['String']['input']>;
  headlineHasSuffix?: InputMaybe<Scalars['String']['input']>;
  headlineIn?: InputMaybe<Array<Scalars['String']['input']>>;
  headlineIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  headlineLT?: InputMaybe<Scalars['String']['input']>;
  headlineLTE?: InputMaybe<Scalars['String']['input']>;
  headlineNEQ?: InputMaybe<Scalars['String']['input']>;
  headlineNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  headlineNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** last_name field predicates */
  lastName?: InputMaybe<Scalars['String']['input']>;
  lastNameContains?: InputMaybe<Scalars['String']['input']>;
  lastNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  lastNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  lastNameGT?: InputMaybe<Scalars['String']['input']>;
  lastNameGTE?: InputMaybe<Scalars['String']['input']>;
  lastNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  lastNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  lastNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  lastNameIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  lastNameLT?: InputMaybe<Scalars['String']['input']>;
  lastNameLTE?: InputMaybe<Scalars['String']['input']>;
  lastNameNEQ?: InputMaybe<Scalars['String']['input']>;
  lastNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  lastNameNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  not?: InputMaybe<__SHOULD_NOT_USE__ProfileWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__ProfileWhereInput>>;
  /** raw_data_s3_key field predicates */
  rawDataS3Key?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyContains?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyContainsFold?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyEqualFold?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyGT?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyGTE?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyHasPrefix?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyHasSuffix?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyIn?: InputMaybe<Array<Scalars['String']['input']>>;
  rawDataS3KeyIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  rawDataS3KeyLT?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyLTE?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyNEQ?: InputMaybe<Scalars['String']['input']>;
  rawDataS3KeyNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  rawDataS3KeyNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** source_file field predicates */
  sourceFile?: InputMaybe<Scalars['String']['input']>;
  sourceFileContains?: InputMaybe<Scalars['String']['input']>;
  sourceFileContainsFold?: InputMaybe<Scalars['String']['input']>;
  sourceFileEqualFold?: InputMaybe<Scalars['String']['input']>;
  sourceFileGT?: InputMaybe<Scalars['String']['input']>;
  sourceFileGTE?: InputMaybe<Scalars['String']['input']>;
  sourceFileHasPrefix?: InputMaybe<Scalars['String']['input']>;
  sourceFileHasSuffix?: InputMaybe<Scalars['String']['input']>;
  sourceFileIn?: InputMaybe<Array<Scalars['String']['input']>>;
  sourceFileIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  sourceFileLT?: InputMaybe<Scalars['String']['input']>;
  sourceFileLTE?: InputMaybe<Scalars['String']['input']>;
  sourceFileNEQ?: InputMaybe<Scalars['String']['input']>;
  sourceFileNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  sourceFileNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** title field predicates */
  title?: InputMaybe<Scalars['String']['input']>;
  titleContains?: InputMaybe<Scalars['String']['input']>;
  titleContainsFold?: InputMaybe<Scalars['String']['input']>;
  titleEqualFold?: InputMaybe<Scalars['String']['input']>;
  titleGT?: InputMaybe<Scalars['String']['input']>;
  titleGTE?: InputMaybe<Scalars['String']['input']>;
  titleHasPrefix?: InputMaybe<Scalars['String']['input']>;
  titleHasSuffix?: InputMaybe<Scalars['String']['input']>;
  titleIn?: InputMaybe<Array<Scalars['String']['input']>>;
  titleIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  titleLT?: InputMaybe<Scalars['String']['input']>;
  titleLTE?: InputMaybe<Scalars['String']['input']>;
  titleNEQ?: InputMaybe<Scalars['String']['input']>;
  titleNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  titleNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** urn field predicates */
  urn?: InputMaybe<Scalars['String']['input']>;
  urnContains?: InputMaybe<Scalars['String']['input']>;
  urnContainsFold?: InputMaybe<Scalars['String']['input']>;
  urnEqualFold?: InputMaybe<Scalars['String']['input']>;
  urnGT?: InputMaybe<Scalars['String']['input']>;
  urnGTE?: InputMaybe<Scalars['String']['input']>;
  urnHasPrefix?: InputMaybe<Scalars['String']['input']>;
  urnHasSuffix?: InputMaybe<Scalars['String']['input']>;
  urnIn?: InputMaybe<Array<Scalars['String']['input']>>;
  urnLT?: InputMaybe<Scalars['String']['input']>;
  urnLTE?: InputMaybe<Scalars['String']['input']>;
  urnNEQ?: InputMaybe<Scalars['String']['input']>;
  urnNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** username field predicates */
  username?: InputMaybe<Scalars['String']['input']>;
  usernameContains?: InputMaybe<Scalars['String']['input']>;
  usernameContainsFold?: InputMaybe<Scalars['String']['input']>;
  usernameEqualFold?: InputMaybe<Scalars['String']['input']>;
  usernameGT?: InputMaybe<Scalars['String']['input']>;
  usernameGTE?: InputMaybe<Scalars['String']['input']>;
  usernameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  usernameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  usernameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  usernameIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  usernameLT?: InputMaybe<Scalars['String']['input']>;
  usernameLTE?: InputMaybe<Scalars['String']['input']>;
  usernameNEQ?: InputMaybe<Scalars['String']['input']>;
  usernameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  usernameNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type __SHOULD_NOT_USE__Query = {
  cronJobConfig: Maybe<__SHOULD_NOT_USE__CronJobConfig>;
  cronJobConfigs: Array<__SHOULD_NOT_USE__CronJobConfig>;
  currentQuotaStatus: Maybe<__SHOULD_NOT_USE__ApiQuotaTracker>;
  dashboardOverview: __SHOULD_NOT_USE__DashboardOverview;
  jobExecutionHistory: Maybe<__SHOULD_NOT_USE__JobExecutionHistory>;
  jobExecutionHistoryList: __SHOULD_NOT_USE__JobExecutionHistoryConnection;
  jobStats: __SHOULD_NOT_USE__JobStats;
  latestJobExecution: Maybe<__SHOULD_NOT_USE__JobExecutionHistory>;
  node: Maybe<__SHOULD_NOT_USE__Node>;
  profile: Maybe<__SHOULD_NOT_USE__Profile>;
  profileEntries: Maybe<__SHOULD_NOT_USE__ProfileEntryConnection>;
  profileEntry: Maybe<__SHOULD_NOT_USE__ProfileEntry>;
  profileEntryStats: __SHOULD_NOT_USE__ProfileEntryStats;
  profilePosts: Maybe<__SHOULD_NOT_USE__ProfilePost>;
  profiles: Maybe<__SHOULD_NOT_USE__ProfileConnection>;
  profilesByTitle: Array<__SHOULD_NOT_USE__ProfileTitleGroup>;
  quotaHistory: Array<__SHOULD_NOT_USE__ApiQuotaTracker>;
  quotaStatus: Maybe<__SHOULD_NOT_USE__ApiQuotaTracker>;
  todo: Maybe<__SHOULD_NOT_USE__Todo>;
  todos: Maybe<__SHOULD_NOT_USE__TodoConnection>;
  user: Maybe<__SHOULD_NOT_USE__User>;
  users: Maybe<__SHOULD_NOT_USE__UserConnection>;
};


export type __SHOULD_NOT_USE__QueryCronJobConfigArgs = {
  jobName: Scalars['String']['input'];
};


export type __SHOULD_NOT_USE__QueryJobExecutionHistoryArgs = {
  id: Scalars['ID']['input'];
};


export type __SHOULD_NOT_USE__QueryJobExecutionHistoryListArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<__SHOULD_NOT_USE__JobExecutionHistoryWhereInput>;
};


export type __SHOULD_NOT_USE__QueryJobStatsArgs = {
  days?: InputMaybe<Scalars['Int']['input']>;
  jobName: Scalars['String']['input'];
  month?: InputMaybe<Scalars['Int']['input']>;
  year?: InputMaybe<Scalars['Int']['input']>;
};


export type __SHOULD_NOT_USE__QueryLatestJobExecutionArgs = {
  jobName: Scalars['String']['input'];
};


export type __SHOULD_NOT_USE__QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type __SHOULD_NOT_USE__QueryProfileArgs = {
  id: Scalars['ID']['input'];
};


export type __SHOULD_NOT_USE__QueryProfileEntriesArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<__SHOULD_NOT_USE__ProfileEntryWhereInput>;
};


export type __SHOULD_NOT_USE__QueryProfileEntryArgs = {
  id: Scalars['ID']['input'];
};


export type __SHOULD_NOT_USE__QueryProfilePostsArgs = {
  username: Scalars['String']['input'];
};


export type __SHOULD_NOT_USE__QueryProfilesArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<__SHOULD_NOT_USE__ProfileWhereInput>;
};


export type __SHOULD_NOT_USE__QueryProfilesByTitleArgs = {
  minCount: Scalars['Int']['input'];
  searchTerm?: InputMaybe<Scalars['String']['input']>;
};


export type __SHOULD_NOT_USE__QueryQuotaHistoryArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};


export type __SHOULD_NOT_USE__QueryQuotaStatusArgs = {
  month: Scalars['Int']['input'];
  year: Scalars['Int']['input'];
};


export type __SHOULD_NOT_USE__QueryTodoArgs = {
  input?: InputMaybe<__SHOULD_NOT_USE__TodoWhereInput>;
};


export type __SHOULD_NOT_USE__QueryTodosArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<__SHOULD_NOT_USE__TodoWhereInput>;
};


export type __SHOULD_NOT_USE__QueryUserArgs = {
  id?: InputMaybe<Scalars['ID']['input']>;
};


export type __SHOULD_NOT_USE__QueryUsersArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<__SHOULD_NOT_USE__UserWhereInput>;
};

export type __SHOULD_NOT_USE__RefreshTokenPayload = {
  accessToken: Scalars['String']['output'];
  refreshToken: Scalars['String']['output'];
};

export type __SHOULD_NOT_USE__Todo = __SHOULD_NOT_USE__Node & {
  createdAt: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  priority: Scalars['Int']['output'];
  status: TodoStatus;
  updatedAt: Scalars['String']['output'];
  userID: Maybe<Scalars['ID']['output']>;
};

export type __SHOULD_NOT_USE__TodoConnection = {
  edges: Maybe<Array<Maybe<__SHOULD_NOT_USE__TodoEdge>>>;
  pageInfo: __SHOULD_NOT_USE__PageInfo;
  totalCount: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__TodoEdge = {
  cursor: Scalars['Cursor']['output'];
  node: Maybe<__SHOULD_NOT_USE__Todo>;
};

export const TodoStatus = {
  Completed: 'COMPLETED',
  InProgress: 'IN_PROGRESS'
} as const;

export type TodoStatus = typeof TodoStatus[keyof typeof TodoStatus];
/**
 * TodoWhereInput is used for filtering Todo objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__TodoWhereInput = {
  and?: InputMaybe<Array<__SHOULD_NOT_USE__TodoWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** user edge predicates */
  hasUser?: InputMaybe<Scalars['Boolean']['input']>;
  hasUserWith?: InputMaybe<Array<__SHOULD_NOT_USE__UserWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__TodoWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__TodoWhereInput>>;
  /** priority field predicates */
  priority?: InputMaybe<Scalars['Int']['input']>;
  priorityGT?: InputMaybe<Scalars['Int']['input']>;
  priorityGTE?: InputMaybe<Scalars['Int']['input']>;
  priorityIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  priorityLT?: InputMaybe<Scalars['Int']['input']>;
  priorityLTE?: InputMaybe<Scalars['Int']['input']>;
  priorityNEQ?: InputMaybe<Scalars['Int']['input']>;
  priorityNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** status field predicates */
  status?: InputMaybe<TodoStatus>;
  statusIn?: InputMaybe<Array<TodoStatus>>;
  statusNEQ?: InputMaybe<TodoStatus>;
  statusNotIn?: InputMaybe<Array<TodoStatus>>;
  /** user_id field predicates */
  userID?: InputMaybe<Scalars['ID']['input']>;
  userIDContains?: InputMaybe<Scalars['ID']['input']>;
  userIDContainsFold?: InputMaybe<Scalars['ID']['input']>;
  userIDEqualFold?: InputMaybe<Scalars['ID']['input']>;
  userIDGT?: InputMaybe<Scalars['ID']['input']>;
  userIDGTE?: InputMaybe<Scalars['ID']['input']>;
  userIDHasPrefix?: InputMaybe<Scalars['ID']['input']>;
  userIDHasSuffix?: InputMaybe<Scalars['ID']['input']>;
  userIDIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  userIDIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  userIDLT?: InputMaybe<Scalars['ID']['input']>;
  userIDLTE?: InputMaybe<Scalars['ID']['input']>;
  userIDNEQ?: InputMaybe<Scalars['ID']['input']>;
  userIDNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  userIDNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type __SHOULD_NOT_USE__UpdateCronJobConfigInput = {
  adminEmail?: InputMaybe<Scalars['String']['input']>;
  batchSize?: InputMaybe<Scalars['Int']['input']>;
  enabled?: InputMaybe<Scalars['Boolean']['input']>;
  respectQuota?: InputMaybe<Scalars['Boolean']['input']>;
  schedule?: InputMaybe<Scalars['String']['input']>;
};

export type __SHOULD_NOT_USE__UpdateProfileEntryInput = {
  gender?: InputMaybe<Scalars['String']['input']>;
  linkedinUrn?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<ProfileEntryStatus>;
};

export type __SHOULD_NOT_USE__UpdateProfileInput = {
  id: Scalars['ID']['input'];
  name?: InputMaybe<Scalars['String']['input']>;
  sourceFile?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  urn?: InputMaybe<Scalars['String']['input']>;
};

export type __SHOULD_NOT_USE__UpdateTodoInput = {
  id: Scalars['ID']['input'];
  name?: InputMaybe<Scalars['String']['input']>;
  priority?: InputMaybe<Scalars['Int']['input']>;
  status?: InputMaybe<TodoStatus>;
  userID?: InputMaybe<Scalars['ID']['input']>;
};

export type __SHOULD_NOT_USE__UpdateUserInput = {
  age?: InputMaybe<Scalars['Int']['input']>;
  id: Scalars['ID']['input'];
  name?: InputMaybe<Scalars['String']['input']>;
};

export type __SHOULD_NOT_USE__User = __SHOULD_NOT_USE__Node & {
  age: Scalars['Int']['output'];
  createdAt: Scalars['String']['output'];
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  todos: Array<__SHOULD_NOT_USE__Todo>;
  updatedAt: Scalars['String']['output'];
};

export type __SHOULD_NOT_USE__UserConnection = {
  edges: Maybe<Array<Maybe<__SHOULD_NOT_USE__UserEdge>>>;
  pageInfo: __SHOULD_NOT_USE__PageInfo;
  totalCount: Scalars['Int']['output'];
};

export type __SHOULD_NOT_USE__UserEdge = {
  cursor: Scalars['Cursor']['output'];
  node: Maybe<__SHOULD_NOT_USE__User>;
};

/**
 * UserWhereInput is used for filtering User objects.
 * Input was generated by ent.
 */
export type __SHOULD_NOT_USE__UserWhereInput = {
  /** age field predicates */
  age?: InputMaybe<Scalars['Int']['input']>;
  ageGT?: InputMaybe<Scalars['Int']['input']>;
  ageGTE?: InputMaybe<Scalars['Int']['input']>;
  ageIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  ageLT?: InputMaybe<Scalars['Int']['input']>;
  ageLTE?: InputMaybe<Scalars['Int']['input']>;
  ageNEQ?: InputMaybe<Scalars['Int']['input']>;
  ageNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  and?: InputMaybe<Array<__SHOULD_NOT_USE__UserWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** email field predicates */
  email?: InputMaybe<Scalars['String']['input']>;
  emailContains?: InputMaybe<Scalars['String']['input']>;
  emailContainsFold?: InputMaybe<Scalars['String']['input']>;
  emailEqualFold?: InputMaybe<Scalars['String']['input']>;
  emailGT?: InputMaybe<Scalars['String']['input']>;
  emailGTE?: InputMaybe<Scalars['String']['input']>;
  emailHasPrefix?: InputMaybe<Scalars['String']['input']>;
  emailHasSuffix?: InputMaybe<Scalars['String']['input']>;
  emailIn?: InputMaybe<Array<Scalars['String']['input']>>;
  emailLT?: InputMaybe<Scalars['String']['input']>;
  emailLTE?: InputMaybe<Scalars['String']['input']>;
  emailNEQ?: InputMaybe<Scalars['String']['input']>;
  emailNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** todos edge predicates */
  hasTodos?: InputMaybe<Scalars['Boolean']['input']>;
  hasTodosWith?: InputMaybe<Array<__SHOULD_NOT_USE__TodoWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<__SHOULD_NOT_USE__UserWhereInput>;
  or?: InputMaybe<Array<__SHOULD_NOT_USE__UserWhereInput>>;
};
