// Generated by `yarn new:queryMock`
import { server } from '../../server'
import { usersQuery } from '../users';
import { type Options } from './type'

export const setUsersQuery = (options: Options) => {
  server.use(usersQuery(options))
}
