// Generated by `yarn new:queryMock`
import type { UsersQuery as Query } from '@graphql/types/index.mock'
import type deepmerge from 'deepmerge';
import { type DeepPartial } from 'utility-types'

export type Response = DeepPartial<Query>
export type { UsersQuery as Query } from '@graphql/types/index.mock'

export type Options = {
  res?: Response;
  networkError?: boolean;
  deepMergeOptions?: deepmerge.Options;
};
