query Profiles(
  $after: Cursor
  $first: Int
  $before: Cursor
  $last: Int
  $where: ProfileWhereInput
) {
  profiles(after: $after, before: $before, first: $first, last: $last, where: $where) {
    edges {
      node {
        ...Profile
      }
    }
    pageInfo {
      ...PageInfo
    }
    totalCount
  }
}
