// Generated by `yarn new:queryMock`
import { usersQuery } from './users'
import { verifyAccessTokenQuery } from './verifyAccessToken'

export const handlers = [
    verifyAccessTokenQuery(),
    usersQuery(),
  ]
