// Generated by `yarn new:queryMock`
import { server } from '../../server'
import { verifyAccessTokenQuery } from '../verifyAccessToken';
import { type Options } from './type'

export const setVerifyAccessTokenQuery = (options: Options) => {
  server.use(verifyAccessTokenQuery(options))
}
