// Generated by `yarn new:queryMock`
import { graphql , HttpResponse } from 'msw'

import { data } from './data'
import type { Options, Query } from './type';

export const verifyAccessTokenQuery = (options?: Options) => {
  return graphql.query<Query>('VerifyAccessToken', () => {
      if (options?.networkError) {
      return HttpResponse.json(
        {
        errors: [
          {
            message: 'Network request failed',
          },
        ],
       },
        { status: 500 }
      );
    }

     return  HttpResponse.json({ data: data(options?.res, options?.deepMergeOptions)})  
  })
}
